name: Compile and Release
on: push
jobs:
  Compile:
    name: Compile
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Ahk2Exe
        uses: CCCC-L/Action-Ahk2Exe@main
        with:
          in: GenshinClicker.ahk
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: x86-binary
          path: GenshinClicker.exe
          retention-days: 90 # max
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: GenshinClicker.exe
        env:
          GITHUB_TOKEN: ${{secrets.GHTOKEN}}
